name: CI with Maven, Coveralls, and PIT in Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      workdir: aggregator-module

    name: Build with Java 8, Coveralls, and PIT on Linux
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-jdk8-${{ hashFiles('**/pom.xml', '**/linux-coveralls.yml') }}
        restore-keys: ${{ runner.os }}-m2-jdk8-
    - name: Build with Maven
      run: mvn verify -Pcoveralls,pit -DrepoToken=$COVERALLS_REPO_TOKEN -DpullRequest=${{ github.event.pull_request.number }}
      working-directory: ${{ env.workdir }}
      env: 
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    - name: Generate JUnit Report
      run: mvn surefire-report:report-only site:site -DgenerateReports=false
      working-directory: ${{ env.workdir }}
      if: ${{ always() }}
    - name: Archive Generated Reports
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: reports
        path: |
          **/target/site
          **/target/pit-reports
