name: CI with Maven, Coveralls, and PIT on Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      workdir: aggregator-module

    name: Build with Java 11, Coveralls, and PIT on Linux
    steps:
    - uses: actions/checkout@v2
      with:
        # Shallow clones should be disabled for a better relevancy of SonarQube analysis
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-m2-jdk11-${{ hashFiles('**/pom.xml', '**/linux-coveralls.yml') }}
        restore-keys: ${{ runner.os }}-m2-jdk11-
    - name: Build with Maven
      run: >
        mvn verify -Pcoveralls,pit sonar:sonar
        -DrepoToken=$COVERALLS_TOKEN -DpullRequest=${{ github.event.pull_request.number }}
        -Dsonar.organization=jasonravagli-github -Dsonar.host.url=https://sonarcloud.io
      working-directory: ${{ env.workdir }}
      env: 
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Generate JUnit Report
      run: mvn surefire-report:report-only site:site -DgenerateReports=false
      working-directory: ${{ env.workdir }}
      if: ${{ always() }}
    - name: Archive Generated Reports
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: reports
        path: |
          **/target/site
          **/target/pit-reports
