name: CI with Maven and Coveralls in Linux

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      workdir: aggregator-module
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            java: 11
          - os: macos-11
            java: 8
          - os: windows-2019
            java: 8

    name: Build with Java 8 and Converalls on Linux
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml', '**/other-platforms.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      run: mvn verify
      working-directory: ${{ env.workdir }}
    - name: Generate JUnit Report
      run: mvn surefire-report:report-only site:site -DgenerateReports=false
      working-directory: ${{ env.workdir }}
      if: ${{ always() }}
    - name: Archive JUnit Report
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: surefire-report
        path: '**/target/site'
