name: CI with Maven and Java 8 on Linux, MacOS, and Windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      workdir: aggregator
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            java: 8
          - os: macos-11
            java: 8
          - os: windows-2019
            java: 8

    name: Build with Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Install Docker on MacOS
      if: runner.os == 'macOS'
      uses: docker-practice/actions-setup-docker@master
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        # Do not cache the artifacts installed during the install phase
        path: |
          ~/.m2
          !/.m2/repository/it/jasonravagli/gym/**
        key: ${{ runner.os }}-m2-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml', '**/other-platforms.yml') }}
        restore-keys: ${{ runner.os }}-m2-jdk${{ matrix.java }}-
    - name: Build with Maven on ${{ runner.os }}
      if: runner.os != 'Linux'
      run: mvn install
      working-directory: ${{ env.workdir }}
    - name: Build with Maven on Linux
      if: runner.os == 'Linux'
      run: xvfb-run mvn install
      working-directory: ${{ env.workdir }}
    - name: Generate JUnit Report
      run: mvn surefire-report:report-only surefire-report:failsafe-report-only site:site -DgenerateReports=false
      working-directory: ${{ env.workdir }}
      if: ${{ always() }}
    - name: Archive JUnit Report
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: surefire-reports-${{ runner.os }}-jdk${{ matrix.java }}
        path: |
          **/target/site
